config/routes.rb
Qrcodesapp::Application.routes.draw do
  resources :qrcodes

  root 'qrcodes#index'

end

app/models/qrcode.rb
class Qrcode < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/qrcodes_controller.rb
class QrcodesController < ApplicationController
  def index
    @codes = Qrcode.all
  end

  def update
  end

  def create
    @qrcode = Qrcode.new(qrdata_params)
    @qrcode.save
  end

  def show
    @qrcode = Qrcode.find(params[:id])
  end

 private
  def qrdata_params
      params.require(:qrdata).permit(:lastname,:firstname,:organization,:jobtitle,:email,:url,:phone,:officephone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/qrcodes_helper.rb
module QrcodesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Qrcodesapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/qrcodes/backup.index.html.erb
<%= form_tag("search", method: "get") do %>
  
    <%= label_tag(:lastname, "Фамилия:") %>
    <%= text_field_tag(:@lastname) %>
    <br>
    <%= label_tag(:firstname,"Имя") %>
    <%= text_field_tag(:firstname) %>
    <br>
    <%= label_tag(:organization,"Организация") %>
    <%= text_field_tag(:firstname, "DataLine") %>
    <br>
    <%= label_tag(:jobtitle,"Должность") %>
    <%= text_field_tag(:jobtitle) %>
    <br>
    <%= label_tag(:email,"E-mail") %>
    <%= text_field_tag(:email ) %>
    <br>
    <%= label_tag(:url,"URL") %>
    <%= text_field_tag(:url,"www.dtln.ru") %>
    <br>
    <%= label_tag(:phone,"Мобильный телефон") %>
    <%= text_field_tag(:phone) %>
    <br>
    <%= label_tag(:officephone,"Рабочий телефон") %>
    <%= text_field_tag(:officephone,) %>
    <br>

    <%= submit_tag("Search") %>
  <% end %>

<% form_for :post do |p| %>

  <%= p.label :lastname %>
  <%= p.text_area :lastname %>

  <%= p.submit %>
<% end %>

<table>
  <tr>
    <td>ФИО</td>
  </tr>

  <%  @codes.each do |code| %>
  <tr>
    <td><%= code.lastname + code.firstname %></td>
  </tr>
<% end  %>
</table>

app/views/qrcodes/index.html.erb
<%= form_for :qrdata, url: qrcodes_path do |qr| %>
  <p>
    <%= qr.label "Фамилия: " %>
    <%= qr.text_field :lastname %>
 </p>
       
  <p>
    <%= qr.label "Имя " %>
    <%= qr.text_field :firstname %>
  </p>

  <p>
    <%= qr.label "Организация " %>
    <%= qr.text_field :organization %>
 </p>
  <p>
    <%= qr.label "Должность " %>
    <%= qr.text_field :jobtitle %>
 </p>
  <p>
    <%= qr.label "E-mail: " %>
    <%= qr.text_field :email %>
 </p>
  <p>
  <%=   qr.label "URL: "%>
    <%= qr.text_field :url %>
 </p>
  <p>
    <%= qr.label "Мобильный телефон: " %>
    <%= qr.text_field :phone %>    
 </p>
    <%= qr.label "Рабочий телефон: " %>
    <%= qr.text_field :officephone %>
 </p>
                 
 <p>
  <%= qr.submit %>
 </p>
<% end %>

  <table border="1">
  <tr>
    <th>Фамилия</th>
    <th>Имя</th>
    <th>Организация</th>
    <th>Должность</th>
    <th>E-mail</th>
    <th>URL</th>
    <th>Мобильный телефон</th>
    <th>Рабочий телефон</th>
  </tr>
  <% @codes.each do |qr|  %>
  <tr>
    <td><%= qr.lastname %></td>
    <td><%= qr.firstname %></td>
    <td><%= qr.organization %></td>
    <td><%= qr.jobtitle %></td>
    <td><%= qr.email %></td>
    <td><%= qr.url %></td>
    <td><%= qr.phone %></td>
    <td><%= qr.officephone %></td>
  </tr>
<% end %>
</table>

app/views/qrcodes/show.html.erb
<table border="1">
  <tr>
      <th>Фамилия</th>
    </tr>
    <tr>
      <td> <%= @qrcode.lastname %> </td>
    </tr>
</table>